### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by itsuki-hayashi** [friends-of-reactphp/espresso#2]
I would be happy to see Igor Wiedler to integrate his two awesome PHP projects. React PHP is great but the ev extension doesn't come with PHP's Official distro hence it is not possible to use React PHP in PaaS hosting and it still lack a good micro-framework like Silex.

**Comment by zender** [comment]
what is the status of this project? Can we use it in production?

**Comment by praswicaksono** [comment]
ReactPHP it self still considered as experimental, so it not safe to use in production environment.

**Comment by sinasalek** [comment]
We're using it on production for over a year and it works well

**Comment by msfidelis** [comment]
Do not let the project die
